In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
diabetics_prediction=pd.read_csv('C:\\Users\\IDEAL COM\\Downloads\\archive (29)\\diabetes.csv')

In [3]:
diabetics_prediction.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [4]:
diabetics_prediction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
diabetics_prediction.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
diabetics_prediction.shape

(768, 9)

In [7]:
diabetics_prediction['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [8]:
diabetics_prediction.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  ...        BMI  DiabetesPedigreeFunction        Age
Outcome                                          ...                                                
0           3.298000  109.980000      68.184000  ...  30.304200                  0.429734  31.190000
1           4.865672  141.257463      70.824627  ...  35.142537                  0.550500  37.067164

[2 rows x 8 columns]

In [9]:
x=diabetics_prediction.drop(columns='Outcome',axis=1)
y=diabetics_prediction['Outcome']

In [10]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age
0              6      148             72             35        0  33.6                     0.627   50
1              1       85             66             29        0  26.6                     0.351   31
2              8      183             64              0        0  23.3                     0.672   32
3              1       89             66             23       94  28.1                     0.167   21
4              0      137             40             35      168  43.1                     2.288   33
..           ...      ...            ...            ...      ...   ...                       ...  ...
763           10      101             76             48      180  32.9                     0.171   63
764            2      122             70             27        0  36.8                     0.340   27
765            5      121             72             23      112  26.2                     0.245   30
766            1      126             60              0        0  30.1                     0.349   47
767            1       93             70             31        0  30.4                     0.315   23

[768 rows x 8 columns]

In [11]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler=StandardScaler()
standerddata=scaler.fit_transform(x)

In [17]:
standerddata

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [40]:
x=standerddata

In [19]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(768, 8)
(614, 8)
(154, 8)


In [22]:
classifier=svm.SVC(kernel='linear')
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [24]:
x_train_prediction=classifier.predict(x_train)
accuracy_train_data=accuracy_score(x_train_prediction,y_train)
accuracy_train_data

0.7719869706840391

In [25]:
x_test_prediction=classifier.predict(x_test)
accuracy_test_data=accuracy_score(x_test_prediction,y_test)
accuracy_test_data

0.7597402597402597

In [30]:
input_data=[1,103,30,38,83,43.3,0.183,33]
input_data_numpy_array=np.asarray(input_data)

input_data_reshape=input_data_numpy_array.reshape(1,-1)
std_data=scaler.transform(input_data_reshape)

prediction=classifier.predict(std_data)

prediction

C:\Users\IDEAL COM\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [31]:
import pickle

In [32]:
filename='trained_model.sav'
pickle.dump(classifier,open(filename,'wb'))

In [33]:
load_model=pickle.load(open('trained_model.sav','rb'))

In [38]:
input_data=[1,103,30,38,83,43.3,0.183,33]
input_data_numpy_array=np.asarray(input_data)

input_data_reshape=input_data_numpy_array.reshape(1,-1)
#std_data=scaler.transform(input_data_reshape)

prediction=load_model.predict(input_data_reshape)

print(prediction)



[1]


In [39]:
if (prediction[0]==0):
    print('Person are not diabets')
else:
    print('Person are diabets')
    

Person are diabets
